import { Carousel } from 'antd'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {
  const contentStyle = {
    height: '160px',
    color: '#fff',
    lineHeight: '160px',
    textAlign: 'center',
    background: '#364d79',
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>مرات یار</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel autoplay>
          
          {
            posts.map((post, i) => (
              <div key={i}><h3 style={contentStyle} ><i> { post._id } </i> { post.title }  { post.content } </h3></div>
          ))
          }
      </Carousel>
      <main className={styles.main}>
        
        <h6>به مرات یار خوش آمدید</h6>
        <h5>به مرات یار خوش آمدید</h5>
        <h4>به مرات یار خوش آمدید</h4>
        <h3>به مرات یار خوش آمدید</h3>
        <h2>به مرات یار خوش آمدید</h2>
        <h1>به مرات یار خوش آمدید</h1>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <hr></hr>
        
      </main>

    </div>
  )
}

export async function getServerSideProps(ctx) {

    let dev = process.env.NODE_ENV !== 'production';
    let { DEV_URL, PROD_URL } = process.env;
    let response = await fetch(`${dev ? DEV_URL : PROD_URL}/api/posts`);
    let data = await response.json();

    return {
        props: {
            posts: data['message'],
        },
    };
}