import Head from 'next/head'
import HeaderSlider from '../components/slider'
import styles from '../styles/Home.module.css'

export default function Home() {
  // console.log(ppp);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSlider />
      <main className={styles.main}>
        
        <h6>به مرات یار خوش آمدید</h6>
        <h5>به مرات یار خوش آمدید</h5>
        <h4>به مرات یار خوش آمدید</h4>
        <h3>به مرات یار خوش آمدید</h3>
        <h2>به مرات یار خوش آمدید</h2>
        <h1>به مرات یار خوش آمدید</h1>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <hr></hr>
        
      </main>

    </div>
  )
}

